name: Pull Backend
on:
  workflow_dispatch:
jobs:
  build:
    name: Pull Backend
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server & execute commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd go/src/tamiyochi-backend
            git stash
            git pull origin main
            go build
            sudo service tamiyochi-backend stop
            sudo service tamiyochi-backend start
            sudo service nginx restart
